### PR TITLE
Improve WSL documentation

### PR DESCRIPTION
**Pull request by ehmicky**
Based on #7 this PR aims at being more precise as to what [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) precisely does.

### CODE REVIEW

**Review by SteveALee — APPROVED** [review]
Looks good.

I thought of 'run several Linux distributions on Windows' but that's not quite true as kernel is Win.
Also is mostly CLI as X11 etc are not really supported (thought people have hacked them

Anyway, they are both uneeded detail.
I'd forgotton ELF.

**Comment by ehmicky** [comment]
I've added a comment about WSL being CLI-oriented. Thanks for the tip!

**Comment by ehmicky** [comment]
@all-contributors please add @SteveALee for ideas, documentation and talks on Twitter!

**Comment by SteveALee** [comment]
Honored

**Pull request merged**
